### ISSUE TITLE
keys not inputting anymore

### ISSUE THREAD

**Issue by w1t1y** [tanjeffreyz02/auto-maple#19]
Starting from the latest patch, less than a day ago whenever the maplestory window is focused the bot doesn't input keys.

When the bot is enabled and maplestory is the focused window nothing happens. Whenever anything else is in focus it still works obviously but Nexon must've changed how they handle virtual keys or something in the last patch, just wondering if there was any solution to this either through using a different method to input keystrokes or something else.

Thank you,

**Comment by tanjeffreyz02** [comment]
Thanks for letting me know, I'll look into this as soon as possible!

**Comment by tanjeffreyz02** [comment]
Hi, I just tried it again and the key presses are still going through without needing to make any changes to the code. Could you please double check that the command line prompt is running in administrator mode (on the same level as MapleStory)? The Windows shortcut provided [here](https://github.com/tanjeffreyz02/auto-maple/blob/v2/Auto%20Maple.lnk) should already take care of this, but if you prefer to run main.py using a command line, make sure to run the command line first as an administrator. Hope this helps!

**Comment by w1t1y** [comment]
Thank you for your help, I really appreciate it

I am rying to open it in an administrator mode cmd prompt but this is what I am getting back, I must have the permissions set weird or something trying to figure it out now and will let you know if I do.

```
C:\WINDOWS\system32>python C:\auto-maple-2\main.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html

Started video capture.

Started keyboard listener.
Traceback (most recent call last):
  File "C:\auto-maple-2\main.py", line 22, in <module>
    bot = Bot()
  File "C:\auto-maple-2\bot.py", line 98, in __init__
    Bot.alert.load('./assets/alert.mp3')
pygame.error: Couldn't open './assets/alert.mp3'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\auto-maple-2\capture.py", line 50, in _main
    config.MINIMAP_TEMPLATE)
  File "C:\auto-maple-2\utils.py", line 77, in single_match
    result = cv2.matchTemplate(gray, template, cv2.TM_CCOEFF)
cv2.error: OpenCV(4.5.4) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:588: error: (-215:Assertion failed) corr.rows <= img.rows + templ.rows - 1 && corr.cols <= img.cols + templ.cols - 1 in function 'cv::crossCorr'
```
