### ISSUE TITLE
hello，I want to know which RNN model is used。

### ISSUE THREAD

**Issue by simpleeeeee** [tanjeffreyz02/Auto-Maple#2]
hello，I want to know which RNN model is used。

**Comment by tanjeffreyz02** [comment]
Hello! I appreciate the interest, but I don't intend on distributing Auto Maple as it was merely a passion project. Sorry about that!

**Comment by simpleeeeee** [comment]
Hi，jeffrey，I tried to use only the simulated keyboard in the project, but
it didn't work in the game, what's going on?

Jeffrey Tan ***@***.***> 于2021年7月28日周三 上午2:42写道：
