### ISSUE TITLE
rune solver not working for some runes

### ISSUE THREAD

**Issue by bkkwok** [tanjeffreyz02/auto-maple#23]
The rune detector isn't working for certain rune variations, I noticed that it doesn't have much problems with yellow, orange, greenish arrows, but isn't able to solve purple and blueish arrows.  Are you experiencing this as well?  
If the model isn't good enough then I can help by giving you more samples to feed it if needed, just lmk.

EDIT: im using the model your provided here https://drive.google.com/drive/folders/1SPdTNF4KZczoWyWTgfyTBRvLvy7WSGpu

**Comment by tanjeffreyz02** [comment]
Yea unfortunately they're bringing back some of the old colors. The algorithm currently filters the arrow colors first then does classification, so any colors that are complementary to yellow/orange won't show up. I'll try to find a more general approach than this, but yes more samples would always be greatly appreciated! Thanks for offering to help!

**Comment by bkkwok** [comment]
do you prefer a specific format for the images, besides the same aspect ratio as the bot? (low background quality, etc. )?  I was also planning on taking them with the maplestory in game screenshot functionality.

**Comment by br046415** [comment]
I'm also having some issues but the capture.py isn't finding runes at all for me. I've added some logging and I can see that it's trying to detect but even with testing threshold down as far as 50%, it isn't ever finding the rune. I've tried both in 1920x1080 and the default 1366x768 that you had used and had no luck with either. Any advice on the detection never finding a match?

**Comment by bkkwok** [comment]
> I'm also having some issues but the capture.py isn't finding runes at all for me. I've added some logging and I can see that it's trying to detect but even with testing threshold down as far as 50%, it isn't ever finding the rune. I've tried both in 1920x1080 and the default 1366x768 that you had used and had no luck with either. Any advice on the detection never finding a match?
This is a different issue, so I've made a new issue for it. https://github.com/tanjeffreyz02/auto-maple/issues/25

**Comment by tanjeffreyz02** [comment]
I don't really have a preferred format as long as the arrows are visible. But samples where the arrows kind of blend in with the background (hard for even humans) would be super useful in stress-testing new models. Of course, this is a lot rarer so please don't actively search for them, but when they do turn up, a quick screenshot would be really helpful!

**Comment by tanjeffreyz02** [comment]
No worries! I've been collecting some too, I think maybe 20-ish more samples would be enough to start prototyping with, and there's no need to label the samples. Considering the weird colored arrows are rarer, augmenting the existing arrow data by inverting/tuning the colors might actually be better than screenshotting by hand though.
