### ISSUE TITLE
rune undetectable on certain maps

### ISSUE THREAD

**Issue by bkkwok** [tanjeffreyz02/auto-maple#25]
It seems auto-maple is able to detect runes easier on maps with a darker background.  This may be because the template rune image used has a black background?
Lowering the confidence level on rune detection to 0.75 helps, but still on maps with lighter backgrounds runes aren't being detected.

NOTE: I understand that this is a passion project of yours ( @tanjeffreyz02 ), and that fixing this would probably be a chore. I may take a shot at fixing this in the future, its just my computer vision knowledge is low.

**Comment by br046415** [comment]
Would this be solved by having a 2nd reference image for the runes with a lighter background and adding a conditional based on what layout is loaded? I haven't tried swapping around the reference image with one of my own.

**Comment by tanjeffreyz02** [comment]
Ah thanks for letting me know, I've been having this issue in CF1 as well. Those are some great suggestions, I'll definitely try them out. Another option could be to use color filters to isolate the rune icon, which could leave the rest of the background as black.

**Comment by tanjeffreyz02** [comment]
Fixed, filtering by color seems to be working on maps with messy minimaps like CF1.
