### ISSUE TITLE
pygame.error: Failed loading libmpg123-0.dll

### ISSUE THREAD

**Issue by narzolauct2019** [tanjeffreyz02/auto-maple#26]
tried downloading the dll from google and moving the file to the system 32 folder
reinstalled pygame lib a few times
![image](https://user-images.githubusercontent.com/71910461/150921801-657ec7a6-bbed-4019-8388-f6a6c1605edb.png)

**Comment by bkkwok** [comment]
Not entirely sure if this will fix your issue, but
Did you download CUDNN and put the bin files into CUDA's bin directory.
This is where CUDA was installed by default on my system C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin
Also If youre using CUDA 11, CUDNN needs to be 8.1.x

**Comment by w1t1y** [comment]
Read [requirements](https://github.com/tanjeffreyz02/auto-maple/blob/v2/requirements.txt)

you have pygame 2.1.2 not 1.9.6 which is working for auto-maple...

**Comment by dev-milani** [comment]
_Hello how are you?_

_I'll leave the solution below that for my case solved:_

**1 -** Go to the directory where pygame is installed and find the file "libmpg123-0.dll".
On my computer it is in the following directory, but on yours it will be in another: "C:\Users\Felipe\PycharmProjects\PythonExercicios\venv\Lib\site-packages\pygame" (yours will be the same from the venv folder);
**2 -** Copy the "libmpg123-0.dll" file;
**3 -** Go to the system32 folder - "C:\Windows\System32" and paste the "libmpg123-0.dll" file;
**4 -** Go to the SysWOW64 folder - "C:\Windows\SysWOW64" and paste the "libmpg123-0.dll" file;
**5 -** Restart the system;

_This was the only way that worked for me, hope it helps you._
