### ISSUE TITLE
Routines

### ISSUE THREAD

**Issue by whowalkingupme** [tanjeffreyz02/Auto-Maple#3]
How to setting Routines? I can't understand how to write csv file in  Routines file.

**Comment by tanjeffreyz02** [comment]
Hello! [This section](https://github.com/tanjeffreyz02/Auto-Maple#--routines) gives an overview of it, but here's a more detailed explanation below (I'll also add some of this to the Readme):

Points (locations) are created using: *, <x position>, <y position>
There's an optional "adjust" keyword argument to make the character fine-tune to the location.

Labels are created using: @, <label name>
They can be jumped to using the "goto" command.

Settings are updated using: s, <setting name>, <value>
All the editable settings can be found at the bottom of [config.py](https://github.com/tanjeffreyz02/Auto-Maple/blob/version-2/config.py).

Commands are created using: <command name>, <param1>, <param2>, ...
The command names correspond with the class names inside command book files, and the <params...> correspond with the command's \_\_init\_\_ parameters. Keyword arguments are also supported.
