### ISSUE TITLE
Error installing requirements.txt

### ISSUE THREAD

**Issue by liem197** [tanjeffreyz02/auto-maple#31]
`ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)
HINT: You are attempting to install a package literally named "requirements.txt" (which cannot exist). Consider using the '-r' flag to install the packages listed in requirements.txt
ERROR: No matching distribution found for requirements.txt`

trying to run the install for requirements

**Comment by tanjeffreyz02** [comment]
Hi, sorry about that! I made a mistake in the setup instructions, but that should be fixed now in the **[new readme](https://github.com/tanjeffreyz02/auto-maple#--setup).**
