### ISSUE TITLE
Issue with keybinds

### ISSUE THREAD

**Issue by ImMalith** [tanjeffreyz02/auto-maple#33]
Is there a list of keybinds for Kanna? I'm kind of confused on which skills should be on which letter

Thanks! This project is amazing and looks promisng!

**Comment by tanjeffreyz02** [comment]
Hello! The key presses can be found in [kanna.py](https://github.com/tanjeffreyz02/auto-maple/blob/v2/command_books/kanna.py). `'Up'`, `'down'`, `'left'`, and `'right'` represent the arrow keys, but other than those, feel free to change any key presses to whatever your in-game keybinds are! If you want to use a key that is not already in the [KEY_MAP](https://github.com/tanjeffreyz02/auto-maple/blob/c8e1e539900f78d6a83285b1b9d521b8c6b7668e/vkeys.py#L26) in vkeys.py, you can find the key's value on this [website](https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes?redirectedfrom=MSDN) and add it to KEY_MAP. You can name the new key whatever you want, and after adding it, you can use it in the `press`, `key_down`, and `key_up` functions.

Hope this helps!
