### ISSUE TITLE
Could not load dynamic library error

### ISSUE THREAD

**Issue by jaezeu** [tanjeffreyz02/auto-maple#34]
Hi there, seem to be getting the following error message. Can I ask what maybe causing this issue? Thank you :)

Also, Im using CUDA v10.1. Can I ask which version is required? Have already downloaded CUDNN and put the bin files into CUDA's bin directory.

![Screenshot 2022-02-03 045243](https://user-images.githubusercontent.com/48310743/152265941-c1f814cd-e476-4838-b7da-28d2f9210c19.png)

**Comment by tanjeffreyz02** [comment]
Hi, it seems the `cudart64_110.dll` is from CUDA v11.x
https://stackoverflow.com/a/67910708

Let me know if this helps!
