### ISSUE TITLE
way to cope with lie detector

### ISSUE THREAD

**Issue by duncanrevamp** [tanjeffreyz02/auto-maple#37]
Hi first of all thanks for your great work, I've been using it for a while (with customizing code a bit, to get it work with windowed maple).
I'm afraid if this shouldn't be an issue for auto-maple considering it in the first place doesn't contain a feature to handle lie detector, but I'd be grateful if you give me an advice.

I've been using auto-maple and it's been great for like a month, but recently I'm kinda struggling with lie detector.
I got some code and asset added to auto-maple (in uh, notifier.py for the lastest release ig, though my code is based off the older one so it's in capture.py) to emit an alarm when lie detector comes in, and _at first_ it works quite well thanks to cv2 template matching.
But here comes a problem, as I solve detectors repeatedly, they are now getting harder to make match templates as they rotate or become rainbow etc etc etc.
Some of them seem to be in range out of capability of cv2 template matching.

And I think I'm all out dealing with them by simple template matching. So frankly … how are you dealing with them?

ps/ If it's way too off topic or not suitable here for any reason i'd also appreciate if you gave some advice to me in discord (me: Fnas#5715)

**Comment by tanjeffreyz02** [comment]
I don't have any experience dealing with lie detectors, so I'm afraid I won't be able to help much, if at all. Template matching isn't really flexible enough to deal with whatever new lie detectors Nexon might give out, but there might be some method to check whether something on the screen seems "abnormal" (maybe using machine learning)? Other than that, I'm not sure how else to approach this problem, sorry about that!

**Comment by duncanrevamp** [comment]
Thanks, I think I'm gonna try teaching it so it can tell if there's something _abnormal_ on the screen.
Gotta teach myself how to tensorflow first, yikes!
