### ISSUE TITLE
Losing players when moving to the edge of the map

### ISSUE THREAD

**Issue by takimc** [tanjeffreyz02/auto-maple#47]
First, I would like to thank you for creating this tool.
In the course of my use of this tool, I have noticed that there is a problem with it stopping working when a player goes to the edge of the map.
This problem was solved by cropping the player image vertically.
I provide this information in the hope that it will be a better tool.

Also, on another matter, regarding the rune solver, I found that it is a more accurate one by detecting gradients, as I referred to another person's tool. This way you can find arrows that change from orange to green, but also blue and purple arrows.
I have not used github much, so I don't know if I can give out the url of someone else's project. I think this tool would be even more awesome if you referenced that code.

This sentence is using machine translation. Sorry it is hard to read.

**Comment by tanjeffreyz02** [comment]
Thank you for these suggestions, I'll look into implementing them! Regarding the rune solver, it would be great if you could copy and paste the link to that project, and I'll take a look.

**Comment by takimc** [comment]
Thank you for your reply.

https://github.com/6b6576696e/maple-bot

The project with respect to the rune solver is the one mentioned above.

The arrows are described in the "Observations" section of this project.
This project only covers arrows that change from red to green, but the same is true for blue and purple objects.
The color change from the tip of the arrow to the end of the arrow has a rule: red to yellow to green to light blue to blue to purple to red.
Therefore, we need to be somewhat creative in how we look for the gradient by changing the way we look for the color at the tip to one with a higher SV value, not just red. I will tell you that as a result of my ingenuity, I have successfully unlocked 48 out of 50 times!
