### ISSUE TITLE
Notifying on guild/buddy/alliance member entering map

### ISSUE THREAD

**Issue by jae0224** [tanjeffreyz02/auto-maple#48]
Hi Jeffrey I want to edit the code to make it do the same notification on guild, buddy etc players entering the map as well. I know that I can just reuse your current code for unknown players entering the map but I just want to ask where you got the mini map icon for it?

Thanks alot!

**Comment by tanjeffreyz02** [comment]
Hi, I took a screenshot of the minimap and cropped it so that only the player icon was left. Hope that helps!

**Comment by jae0224** [comment]
Yup thanks for the quick reply! ^.^
