### ISSUE TITLE
does the main bot can running without model?

### ISSUE THREAD

**Issue by fuqi1001** [tanjeffreyz02/Auto-Maple#5]
If i remove the rune related code, can i use the other function basically?

**Comment by tanjeffreyz02** [comment]
Hello! Yes, the code should still work correctly.

I think I'll just upload the model. I do want to keep this repo public/viewable, and I realized pushing the code in the first place has already "distributed" it in a way...

**Comment by fuqi1001** [comment]
Really appreciate! Can't wait to try it!

**Comment by fuqi1001** [comment]
Hi, I have install all the pkg and start the main.py, but the process stop at 'Successfully initialized Auto Maple, now accepting commands.' this log, and minimap monitor is red without any action. Do you have any idea with this

**Comment by tanjeffreyz02** [comment]
Hi, there are keybinds in the listener.py's main function. Currently
"insert" enables/disables the bot, "F6" reloads the current routine, "F7"
loads a new command book and new routine, and "F8" displays the character's
current position (useful when writing your own routines).
