### ISSUE TITLE
No Rune Solving

### ISSUE THREAD

**Issue by w1t1y** [tanjeffreyz02/auto-maple#52]
I wanted to use this on my laptop but the graphics card is far from powerful enough, just wondering how I could use it without a rune solver at all and just manually solve runes without it trying to solve and getting stuck.

Cheers.

**Comment by tanjeffreyz02** [comment]
Hi, you can replace [line 83 in bot.py](https://github.com/tanjeffreyz02/auto-maple/blob/cb23be6308afc6dee149096df3b473b38a774735/bot.py#L83) with say `time.sleep(5)` to give yourself 5 seconds to solve the rune. 
You will also need to add `self.rune_active = False` right below line 83 (same indentation). This tells the bot you've solved the rune and it will start looking for the next one.

**Comment by w1t1y** [comment]
I appreciate that, thank you so much.

**Comment by w1t1y** [comment]
Sorry, I tried what you outlined but received this error back when trying to launch the bot.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Andrew\Desktop\auto-maple-2\bot.py", line 63, in _main
    model = detection.load_model()
NameError: name 'detection' is not defined
```

Would really appreciate if you could help in solving this.

Thanks

**Comment by GphantomR** [comment]
Have you figured how to disable rune solving?
