### ISSUE TITLE
hi！jeffreyz,Can you share the training resources for the second branch of the project?

### ISSUE THREAD

**Issue by simpleeeeee** [tanjeffreyz02/Auto-Maple#6]
I want to use it for my own model training

**Comment by tanjeffreyz02** [comment]
Hello! All the training resources besides the model should be in the "rune-detection" branch. Pre-assembled models can be found in the [TensorFlow 2 Model Zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md). These models are very accurate and state-of-the-art, but if you want to understand machine learning at a deeper level, I'd suggest creating and training your own model either using Pytorch or TensorFlow! ([Here's](https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html) a great tutorial to get started with.)

**Comment by Metaforce007** [comment]
> Hello! All the training resources besides the model should be in the "rune-detection" branch. Pre-assembled models can be found in the [TensorFlow 2 Model Zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md). These models are very accurate and state-of-the-art, but if you want to understand machine learning at a deeper level, I'd suggest creating and training your own model either using Pytorch or TensorFlow! ([Here's](https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html) a great tutorial to get started with.)

Hi @tanjeffreyz , is this comment no longer relevant? I've been trying to find the training and classification code to try and train a new model to work with some of the new runes but it seems you did not include it in the repo. Is it possible to have access to it?
