### ISSUE TITLE
Renew Routines 

### ISSUE THREAD

**Issue by nehcap** [tanjeffreyz02/Auto-Maple#8]
the dcup2 routine is old and no kanna farm there anymore if you can make side path routine without tengu its will be great
example: https://www.youtube.com/watch?v=3YM3gmeFj6M&t=157s

**Comment by tanjeffreyz02** [comment]
Hi, I actually stopped playing MapleStory once I finished writing Auto Maple. However, the readme for this project contains an explanation of how to create your own routines. You can find it [here](https://github.com/tanjeffreyz02/Auto-Maple#--routines).

**Comment by nehcap** [comment]
how i can know the pos of every point in the map?

**Comment by nehcap** [comment]
you got discord maybe?

**Comment by tanjeffreyz02** [comment]
Currently, the keybind for taking a snapshot of the character's current position is F8. Feel free to play around with the keybindings in [listener.py](https://github.com/tanjeffreyz02/Auto-Maple/blob/e3699080bde59f361fd1777cca3d416c7ec9d4f9/listener.py)!

**Comment by nehcap** [comment]
ill try make my own csv but if you come back to maple pls make side path one its will be amazing

**Comment by nehcap** [comment]
How i can use layout recorder?
Its recording the movement? how you start it and how you stop?

**Comment by tanjeffreyz02** [comment]
Yeah, if `record_layout` is set to `True`, then the program will automatically record where it has already been in a layout file. This makes later iterations of the routine faster and more accurate because it can just precompute the path it needs to take. Once you're satisfied with how the routine is being executed, you can set `record_layout` to `False` and Auto Maple will continue to use the layout file without editing it.

**Comment by nehcap** [comment]
How i stop it? I must use it or i can just use the points with the routine?

**Comment by nehcap** [comment]
What adjust and counter does?

**Comment by tanjeffreyz02** [comment]
Auto Maple only records player position while `record_layout` is set to `True`, and setting it to `False` would stop it. You don't exactly need to use `record_layout`, but when running complicated routines or messy map layouts, it significantly improves accuracy and speed. The [readme](https://github.com/tanjeffreyz02/Auto-Maple#--routines) has an explanation of the routine keywords like `adjust` and `counter`.
